[package]
name = "roguelike"
version = "0.1.0"
edition = "2024"

[dependencies]
tcod = { git = "https://github.com/tomassedovic/tcod-rs.git", rev = "d4ad074", features = ["serialization"]}
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

